# Generated by Django 5.0.2 on 2024-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_feautred',
            new_name='is_featured',
        ),
        migrations.AlterField(
            model_name='Category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
