# Generated by Django 5.0.2 on 2024-05-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
