# Generated by Django 5.0.2 on 2024-05-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quintity',
        ),
    ]
